### ISSUE TITLE
Fried HDMI port/monitor

### ISSUE THREAD

**Issue by kurtratliff** [thetooth/p4k6kpower#1]
Using a Soonwell P-VG1 Battery plate and Feelworld FW -279 on Pocket 4K.  HDMI port doesn’t work anymore and FW 279 is completely inoperable.  Smoke was even coming out of the monitor and cable were extremely hot.

**Comment by thetooth** [comment]
Thanks, was the HDMI cable a brand name one? Or have you used the same cable in the past without any issues?

**Comment by kurtratliff** [comment]
It was this one:

https://www.amazon.com/dp/B01HQ2H7CS?ref=ppx_pop_mob_ap_share

I had used the setup before but this happened on the first prolonged shoot. 

I know at least one other person on YouTube who said these cheap coiled cables are usually the culprit but that could be anecdotal.  That’s why I love that you’re piecing this together. 


Kurtis Ratliff
